In [25]:
import pandas as pd

In [26]:
import requests
response = requests.get("https://worldpopulationreview.com/state-rankings/starbucks-stores-by-state#google_vignette")

In [27]:
from bs4 import BeautifulSoup
soup = BeautifulSoup(response.content, "html.parser")

In [28]:
table = soup.find("table", class_="wpr-table")
table

<table class="wpr-table"><thead class="table-head bg-wpr-table_header_bg relative z-40 px-0 py-0 text-xs uppercase tracking-wider"><tr><th class="datatable-th bg-wpr-table_header_bg text-wpr-table_header border-wpr-table_border sticky top-0 border-b bg-clip-padding px-3 py-2 text-left align-bottom leading-4 md:px-4 pin left-0 z-50 border-l-0"><div class="flex flex-col items-stretch justify-start"><div class="flex flex-row items-center cursor-pointer select-none">State</div></div></th><th class="datatable-th bg-wpr-table_header_bg text-wpr-table_header border-wpr-table_border sticky top-0 border-b bg-clip-padding px-3 py-2 text-left align-bottom leading-4 md:px-4 z-40"><div class="flex flex-col items-stretch justify-start"><div class="flex flex-row items-center cursor-pointer select-none">Starbucks Stores 2023<svg class="icon icon-tabler icon-tabler-chevron-down" fill="none" height="14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="14" xmlns="http://www.w3.org/2000/svg"><path d="M0 0h24v24H0z" fill="none" stroke="none"></path><polyline points="6 9 12 15 18 9"></polyline></svg></div></div></th><th class="datatable-th bg-wpr-table_header_bg text-wpr-table_header border-wpr-table_border sticky top-0 border-b bg-clip-padding px-3 py-2 text-left align-bottom leading-4 md:px-4 z-40"><div class="flex flex-col items-stretch justify-start"><div class="flex flex-row items-center cursor-pointer select-none">Starbucks Stores 2021</div></div></th><th class="datatable-th bg-wpr-table_header_bg text-wpr-table_header border-wpr-table_border sticky top-0 border-b bg-clip-padding px-3 py-2 text-left align-bottom leading-4 md:px-4 z-40"><div class="flex flex-col items-stretch justify-start"><div class="flex flex-row items-center cursor-pointer select-none">Starbucks Stores 2024</div></div></th></tr></thead><tbody class="relative z-10 text-sm"><tr class="table-row" data-state="false"><th class="text-wpr-table_header sticky left-0 z-50 bg-clip-padding py-1.5 pl-3 text-left align-middle text-sm md:px-4"><a class="text-wpr-link" href="/states/california" to="/states/california">California</a></th><td class="text-wpr-table_text z-40 px-3 py-1.5 text-sm md:px-4">3,080</td><td class="text-wpr-table_text z-40 px-3 py-1.5 text-sm md:px-4">2,959</td><td class="text-wpr-table_text z-40 px-3 py-1.5 text-sm md:px-4">3,117</td></tr><tr class="table-row" data-state="false"><th class="text-wpr-table_header sticky left-0 z-50 bg-clip-padding py-1.5 pl-3 text-left align-middle text-sm md:px-4"><a class="text-wpr-link" href="/states/texas" to="/states/texas">Texas</a></th><td class="text-wpr-table_text z-40 px-3 py-1.5 text-sm md:px-4">1,346</td><td class="text-wpr-table_text z-40 px-3 py-1.5 text-sm md:px-4">1,215</td><td class="text-wpr-table_text z-40 px-3 py-1.5 text-sm md:px-4">1,409</td></tr><tr class="table-row" data-state="false"><th class="text-wpr-table_header sticky left-0 z-50 bg-clip-padding py-1.5 pl-3 text-left align-middle text-sm md:px-4"><a class="text-wpr-link" href="/states/florida" to="/states/florida">Florida</a></th><td class="text-wpr-table_text z-40 px-3 py-1.5 text-sm md:px-4">844</td><td class="text-wpr-table_text z-40 px-3 py-1.5 text-sm md:px-4">786</td><td class="text-wpr-table_text z-40 px-3 py-1.5 text-sm md:px-4">892</td></tr><tr class="table-row" data-state="false"><th class="text-wpr-table_header sticky left-0 z-50 bg-clip-padding py-1.5 pl-3 text-left align-middle text-sm md:px-4"><a class="text-wpr-link" href="/states/washington" to="/states/washington">Washington</a></th><td class="text-wpr-table_text z-40 px-3 py-1.5 text-sm md:px-4">741</td><td class="text-wpr-table_text z-40 px-3 py-1.5 text-sm md:px-4">739</td><td class="text-wpr-table_text z-40 px-3 py-1.5 text-sm md:px-4">736</td></tr><tr class="table-row" data-state="false"><th class="text-wpr-table_header sticky left-0 z-50 bg-clip-padding py-1.5 pl-3 text-left align-middle text-sm md:px-4"><a class="text-wpr-link" href="/states/new-york" to="/states/new-york">New York</a></th><td class="text-wpr-table_text z-40 px-3 py-1.5 text-sm md:px-4">692</td><td class="text-wpr-table_text z-40 px-3 py-1.5 text-sm md:px-4">643</td><td class="text-wpr-table_text z-40 px-3 py-1.5 text-sm md:px-4">715</td></tr><tr class="table-row" data-state="false"><th class="text-wpr-table_header sticky left-0 z-50 bg-clip-padding py-1.5 pl-3 text-left align-middle text-sm md:px-4"><a class="text-wpr-link" href="/states/illinois" to="/states/illinois">Illinois</a></th><td class="text-wpr-table_text z-40 px-3 py-1.5 text-sm md:px-4">677</td><td class="text-wpr-table_text z-40 px-3 py-1.5 text-sm md:px-4">621</td><td class="text-wpr-table_text z-40 px-3 py-1.5 text-sm md:px-4">685</td></tr><tr class="table-row" data-state="false"><th class="text-wpr-table_header sticky left-0 z-50 bg-clip-padding py-1.5 pl-3 text-left align-middle text-sm md:px-4"><a class="text-wpr-link" href="/states/arizona" to="/states/arizona">Arizona</a></th><td class="text-wpr-table_text z-40 px-3 py-1.5 text-sm md:px-4">548</td><td class="text-wpr-table_text z-40 px-3 py-1.5 text-sm md:px-4">535</td><td class="text-wpr-table_text z-40 px-3 py-1.5 text-sm md:px-4">579</td></tr><tr class="table-row" data-state="false"><th class="text-wpr-table_header sticky left-0 z-50 bg-clip-padding py-1.5 pl-3 text-left align-middle text-sm md:px-4"><a class="text-wpr-link" href="/states/colorado" to="/states/colorado">Colorado</a></th><td class="text-wpr-table_text z-40 px-3 py-1.5 text-sm md:px-4">495</td><td class="text-wpr-table_text z-40 px-3 py-1.5 text-sm md:px-4">497</td><td class="text-wpr-table_text z-40 px-3 py-1.5 text-sm md:px-4">506</td></tr><tr class="table-row" data-state="false"><th class="text-wpr-table_header sticky left-0 z-50 bg-clip-padding py-1.5 pl-3 text-left align-middle text-sm md:px-4"><a class="text-wpr-link" href="/states/ohio" to="/states/ohio">Ohio</a></th><td class="text-wpr-table_text z-40 px-3 py-1.5 text-sm md:px-4">491</td><td class="text-wpr-table_text z-40 px-3 py-1.5 text-sm md:px-4">446</td><td class="text-wpr-table_text z-40 px-3 py-1.5 text-sm md:px-4">499</td></tr><tr class="table-row" data-state="false"><th class="text-wpr-table_header sticky left-0 z-50 bg-clip-padding py-1.5 pl-3 text-left align-middle text-sm md:px-4"><a class="text-wpr-link" href="/states/virginia" to="/states/virginia">Virginia</a></th><td class="text-wpr-table_text z-40 px-3 py-1.5 text-sm md:px-4">489</td><td class="text-wpr-table_text z-40 px-3 py-1.5 text-sm md:px-4">456</td><td class="text-wpr-table_text z-40 px-3 py-1.5 text-sm md:px-4">510</td></tr><tr class="table-row" data-state="false"><th class="text-wpr-table_header sticky left-0 z-50 bg-clip-padding py-1.5 pl-3 text-left align-middle text-sm md:px-4"><a class="text-wpr-link" href="/states/oregon" to="/states/oregon">Oregon</a></th><td class="text-wpr-table_text z-40 px-3 py-1.5 text-sm md:px-4">359</td><td class="text-wpr-table_text z-40 px-3 py-1.5 text-sm md:px-4">345</td><td class="text-wpr-table_text z-40 px-3 py-1.5 text-sm md:px-4"></td></tr><tr class="table-row" data-state="false"><th class="text-wpr-table_header sticky left-0 z-50 bg-clip-padding py-1.5 pl-3 text-left align-middle text-sm md:px-4"><a class="text-wpr-link" href="/states/pennsylvania" to="/states/pennsylvania">Pennsylvania</a></th><td class="text-wpr-table_text z-40 px-3 py-1.5 text-sm md:px-4">357</td><td class="text-wpr-table_text z-40 px-3 py-1.5 text-sm md:px-4">406</td><td class="text-wpr-table_text z-40 px-3 py-1.5 text-sm md:px-4"></td></tr><tr class="table-row" data-state="false"><th class="text-wpr-table_header sticky left-0 z-50 bg-clip-padding py-1.5 pl-3 text-left align-middle text-sm md:px-4"><a class="text-wpr-link" href="/states/north-carolina" to="/states/north-carolina">North Carolina</a></th><td class="text-wpr-table_text z-40 px-3 py-1.5 text-sm md:px-4">338</td><td class="text-wpr-table_text z-40 px-3 py-1.5 text-sm md:px-4">422</td><td class="text-wpr-table_text z-40 px-3 py-1.5 text-sm md:px-4"></td></tr><tr class="table-row" data-state="false"><th class="text-wpr-table_header sticky left-0 z-50 bg-clip-padding py-1.5 pl-3 text-left align-middle text-sm md:px-4"><a class="text-wpr-link" href="/states/georgia" to="/states/georgia">Georgia</a></th><td class="text-wpr-table_text z-40 px-3 py-1.5 text-sm md:px-4">326</td><td class="text-wpr-table_text z-40 px-3 py-1.5 text-sm md:px-4">379</td><td class="text-wpr-table_text z-40 px-3 py-1.5 text-sm md:px-4"></td></tr><tr class="table-row" data-state="false"><th class="text-wpr-table_header sticky left-0 z-50 bg-clip-padding py-1.5 pl-3 text-left align-middle text-sm md:px-4"><a class="text-wpr-link" href="/states/michigan" to="/states/michigan">Michigan</a></th><td class="text-wpr-table_text z-40 px-3 py-1.5 text-sm md:px-4">283</td><td class="text-wpr-table_text z-40 px-3 py-1.5 text-sm md:px-4">310</td><td class="text-wpr-table_text z-40 px-3 py-1.5 text-sm md:px-4"></td></tr><tr class="table-row" data-state="false"><th class="text-wpr-table_header sticky left-0 z-50 bg-clip-padding py-1.5 pl-3 text-left align-middle text-sm md:px-4"><a class="text-wpr-link" href="/states/massachusetts" to="/states/massachusetts">Massachusetts</a></th><td class="text-wpr-table_text z-40 px-3 py-1.5 text-sm md:px-4">273</td><td class="text-wpr-table_text z-40 px-3 py-1.5 text-sm md:px-4">279</td><td class="text-wpr-table_text z-40 px-3 py-1.5 text-sm md:px-4"></td></tr><tr class="table-row" data-state="false"><th class="text-wpr-table_header sticky left-0 z-50 bg-clip-padding py-1.5 pl-3 text-left align-middle text-sm md:px-4"><a class="text-wpr-link" href="/states/new-jersey" to="/states/new-jersey">New Jersey</a></th><td class="text-wpr-table_text z-40 px-3 py-1.5 text-sm md:px-4">261</td><td class="text-wpr-table_text z-40 px-3 py-1.5 text-sm md:px-4">293</td><td class="text-wpr-table_text z-40 px-3 py-1.5 text-sm md:px-4"></td></tr><tr class="table-row" data-state="false"><th class="text-wpr-table_header sticky left-0 z-50 bg-clip-padding py-1.5 pl-3 text-left align-middle text-sm md:px-4"><a class="text-wpr-link" href="/states/maryland" to="/states/maryland">Maryland</a></th><td class="text-wpr-table_text z-40 px-3 py-1.5 text-sm md:px-4">257</td><td class="text-wpr-table_text z-40 px-3 py-1.5 text-sm md:px-4">274</td><td class="text-wpr-table_text z-40 px-3 py-1.5 text-sm md:px-4"></td></tr><tr class="table-row" data-state="false"><th class="text-wpr-table_header sticky left-0 z-50 bg-clip-padding py-1.5 pl-3 text-left align-middle text-sm md:px-4"><a class="text-wpr-link" href="/states/nevada" to="/states/nevada">Nevada</a></th><td class="text-wpr-table_text z-40 px-3 py-1.5 text-sm md:px-4">253</td><td class="text-wpr-table_text z-40 px-3 py-1.5 text-sm md:px-4">269</td><td class="text-wpr-table_text z-40 px-3 py-1.5 text-sm md:px-4"></td></tr><tr class="table-row" data-state="false"><th class="text-wpr-table_header sticky left-0 z-50 bg-clip-padding py-1.5 pl-3 text-left align-middle text-sm md:px-4"><a class="text-wpr-link" href="/states/indiana" to="/states/indiana">Indiana</a></th><td class="text-wpr-table_text z-40 px-3 py-1.5 text-sm md:px-4">221</td><td class="text-wpr-table_text z-40 px-3 py-1.5 text-sm md:px-4">265</td><td class="text-wpr-table_text z-40 px-3 py-1.5 text-sm md:px-4"></td></tr><tr class="table-row" data-state="false"><th class="text-wpr-table_header sticky left-0 z-50 bg-clip-padding py-1.5 pl-3 text-left align-middle text-sm md:px-4"><a class="text-wpr-link" href="/states/missouri" to="/states/missouri">Missouri</a></th><td class="text-wpr-table_text z-40 px-3 py-1.5 text-sm md:px-4">188</td><td class="text-wpr-table_text z-40 px-3 py-1.5 text-sm md:px-4">208</td><td class="text-wpr-table_text z-40 px-3 py-1.5 text-sm md:px-4"></td></tr><tr class="table-row" data-state="false"><th class="text-wpr-table_header sticky left-0 z-50 bg-clip-padding py-1.5 pl-3 text-left align-middle text-sm md:px-4"><a class="text-wpr-link" href="/states/minnesota" to="/states/minnesota">Minnesota</a></th><td class="text-wpr-table_text z-40 px-3 py-1.5 text-sm md:px-4">184</td><td class="text-wpr-table_text z-40 px-3 py-1.5 text-sm md:px-4">212</td><td class="text-wpr-table_text z-40 px-3 py-1.5 text-sm md:px-4"></td></tr><tr class="table-row" data-state="false"><th class="text-wpr-table_header sticky left-0 z-50 bg-clip-padding py-1.5 pl-3 text-left align-middle text-sm md:px-4"><a class="text-wpr-link" href="/states/tennessee" to="/states/tennessee">Tennessee</a></th><td class="text-wpr-table_text z-40 px-3 py-1.5 text-sm md:px-4">180</td><td class="text-wpr-table_text z-40 px-3 py-1.5 text-sm md:px-4">237</td><td class="text-wpr-table_text z-40 px-3 py-1.5 text-sm md:px-4"></td></tr><tr class="table-row" data-state="false"><th class="text-wpr-table_header sticky left-0 z-50 bg-clip-padding py-1.5 pl-3 text-left align-middle text-sm md:px-4"><a class="text-wpr-link" href="/states/kentucky" to="/states/kentucky">Kentucky</a></th><td class="text-wpr-table_text z-40 px-3 py-1.5 text-sm md:px-4">166</td><td class="text-wpr-table_text z-40 px-3 py-1.5 text-sm md:px-4">131</td><td class="text-wpr-table_text z-40 px-3 py-1.5 text-sm md:px-4"></td></tr><tr class="table-row" data-state="false"><th class="text-wpr-table_header sticky left-0 z-50 bg-clip-padding py-1.5 pl-3 text-left align-middle text-sm md:px-4"><a class="text-wpr-link" href="/states/wisconsin" to="/states/wisconsin">Wisconsin</a></th><td class="text-wpr-table_text z-40 px-3 py-1.5 text-sm md:px-4">145</td><td class="text-wpr-table_text z-40 px-3 py-1.5 text-sm md:px-4">176</td><td class="text-wpr-table_text z-40 px-3 py-1.5 text-sm md:px-4"></td></tr><tr class="table-row" data-state="false"><th class="text-wpr-table_header sticky left-0 z-50 bg-clip-padding py-1.5 pl-3 text-left align-middle text-sm md:px-4"><a class="text-wpr-link" href="/states/south-carolina" to="/states/south-carolina">South Carolina</a></th><td class="text-wpr-table_text z-40 px-3 py-1.5 text-sm md:px-4">131</td><td class="text-wpr-table_text z-40 px-3 py-1.5 text-sm md:px-4">207</td><td class="text-wpr-table_text z-40 px-3 py-1.5 text-sm md:px-4"></td></tr><tr class="table-row" data-state="false"><th class="text-wpr-table_header sticky left-0 z-50 bg-clip-padding py-1.5 pl-3 text-left align-middle text-sm md:px-4"><a class="text-wpr-link" href="/states/connecticut" to="/states/connecticut">Connecticut</a></th><td class="text-wpr-table_text z-40 px-3 py-1.5 text-sm md:px-4">123</td><td class="text-wpr-table_text z-40 px-3 py-1.5 text-sm md:px-4">125</td><td class="text-wpr-table_text z-40 px-3 py-1.5 text-sm md:px-4"></td></tr><tr class="table-row" data-state="false"><th class="text-wpr-table_header sticky left-0 z-50 bg-clip-padding py-1.5 pl-3 text-left align-middle text-sm md:px-4"><a class="text-wpr-link" href="/states/utah" to="/states/utah">Utah</a></th><td class="text-wpr-table_text z-40 px-3 py-1.5 text-sm md:px-4">101</td><td class="text-wpr-table_text z-40 px-3 py-1.5 text-sm md:px-4">126</td><td class="text-wpr-table_text z-40 px-3 py-1.5 text-sm md:px-4"></td></tr><tr class="table-row" data-state="false"><th class="text-wpr-table_header sticky left-0 z-50 bg-clip-padding py-1.5 pl-3 text-left align-middle text-sm md:px-4"><a class="text-wpr-link" href="/states/hawaii" to="/states/hawaii">Hawaii</a></th><td class="text-wpr-table_text z-40 px-3 py-1.5 text-sm md:px-4">99</td><td class="text-wpr-table_text z-40 px-3 py-1.5 text-sm md:px-4">105</td><td class="text-wpr-table_text z-40 px-3 py-1.5 text-sm md:px-4"></td></tr><tr class="table-row" data-state="false"><th class="text-wpr-table_header sticky left-0 z-50 bg-clip-padding py-1.5 pl-3 text-left align-middle text-sm md:px-4"><a class="text-wpr-link" href="/states/kansas" to="/states/kansas">Kansas</a></th><td class="text-wpr-table_text z-40 px-3 py-1.5 text-sm md:px-4">94</td><td class="text-wpr-table_text z-40 px-3 py-1.5 text-sm md:px-4">120</td><td class="text-wpr-table_text z-40 px-3 py-1.5 text-sm md:px-4"></td></tr><tr class="table-row" data-state="false"><th class="text-wpr-table_header sticky left-0 z-50 bg-clip-padding py-1.5 pl-3 text-left align-middle text-sm md:px-4"><a class="text-wpr-link" href="/states/district-of-columbia" to="/states/district-of-columbia">District of Columbia</a></th><td class="text-wpr-table_text z-40 px-3 py-1.5 text-sm md:px-4">91</td><td class="text-wpr-table_text z-40 px-3 py-1.5 text-sm md:px-4"></td><td class="text-wpr-table_text z-40 px-3 py-1.5 text-sm md:px-4"></td></tr><tr class="table-row" data-state="false"><th class="text-wpr-table_header sticky left-0 z-50 bg-clip-padding py-1.5 pl-3 text-left align-middle text-sm md:px-4"><a class="text-wpr-link" href="/states/iowa" to="/states/iowa">Iowa</a></th><td class="text-wpr-table_text z-40 px-3 py-1.5 text-sm md:px-4">89</td><td class="text-wpr-table_text z-40 px-3 py-1.5 text-sm md:px-4">142</td><td class="text-wpr-table_text z-40 px-3 py-1.5 text-sm md:px-4"></td></tr><tr class="table-row" data-state="false"><th class="text-wpr-table_header sticky left-0 z-50 bg-clip-padding py-1.5 pl-3 text-left align-middle text-sm md:px-4"><a class="text-wpr-link" href="/states/alabama" to="/states/alabama">Alabama</a></th><td class="text-wpr-table_text z-40 px-3 py-1.5 text-sm md:px-4">85</td><td class="text-wpr-table_text z-40 px-3 py-1.5 text-sm md:px-4">99</td><td class="text-wpr-table_text z-40 px-3 py-1.5 text-sm md:px-4"></td></tr><tr class="table-row" data-state="false"><th class="text-wpr-table_header sticky left-0 z-50 bg-clip-padding py-1.5 pl-3 text-left align-middle text-sm md:px-4"><a class="text-wpr-link" href="/states/louisiana" to="/states/louisiana">Louisiana</a></th><td class="text-wpr-table_text z-40 px-3 py-1.5 text-sm md:px-4">84</td><td class="text-wpr-table_text z-40 px-3 py-1.5 text-sm md:px-4">10</td><td class="text-wpr-table_text z-40 px-3 py-1.5 text-sm md:px-4"></td></tr><tr class="table-row" data-state="false"><th class="text-wpr-table_header sticky left-0 z-50 bg-clip-padding py-1.5 pl-3 text-left align-middle text-sm md:px-4"><a class="text-wpr-link" href="/states/oklahoma" to="/states/oklahoma">Oklahoma</a></th><td class="text-wpr-table_text z-40 px-3 py-1.5 text-sm md:px-4">79</td><td class="text-wpr-table_text z-40 px-3 py-1.5 text-sm md:px-4">94</td><td class="text-wpr-table_text z-40 px-3 py-1.5 text-sm md:px-4"></td></tr><tr class="table-row" data-state="false"><th class="text-wpr-table_header sticky left-0 z-50 bg-clip-padding py-1.5 pl-3 text-left align-middle text-sm md:px-4"><a class="text-wpr-link" href="/states/new-mexico" to="/states/new-mexico">New Mexico</a></th><td class="text-wpr-table_text z-40 px-3 py-1.5 text-sm md:px-4">76</td><td class="text-wpr-table_text z-40 px-3 py-1.5 text-sm md:px-4">92</td><td class="text-wpr-table_text z-40 px-3 py-1.5 text-sm md:px-4"></td></tr><tr class="table-row" data-state="false"><th class="text-wpr-table_header sticky left-0 z-50 bg-clip-padding py-1.5 pl-3 text-left align-middle text-sm md:px-4"><a class="text-wpr-link" href="/states/idaho" to="/states/idaho">Idaho</a></th><td class="text-wpr-table_text z-40 px-3 py-1.5 text-sm md:px-4">67</td><td class="text-wpr-table_text z-40 px-3 py-1.5 text-sm md:px-4">78</td><td class="text-wpr-table_text z-40 px-3 py-1.5 text-sm md:px-4"></td></tr><tr class="table-row" data-state="false"><th class="text-wpr-table_header sticky left-0 z-50 bg-clip-padding py-1.5 pl-3 text-left align-middle text-sm md:px-4"><a class="text-wpr-link" href="/states/nebraska" to="/states/nebraska">Nebraska</a></th><td class="text-wpr-table_text z-40 px-3 py-1.5 text-sm md:px-4">58</td><td class="text-wpr-table_text z-40 px-3 py-1.5 text-sm md:px-4">87</td><td class="text-wpr-table_text z-40 px-3 py-1.5 text-sm md:px-4"></td></tr><tr class="table-row" data-state="false"><th class="text-wpr-table_header sticky left-0 z-50 bg-clip-padding py-1.5 pl-3 text-left align-middle 

In [29]:
#1
# initialize an empty list
rows = []

# iterate over all rows in the faculty table
for coffee in table.find_all("tr")[1:]:
    state = coffee.find_all("th")
    cells = coffee.find_all("td")

    # get the state names
    state_tag = state[0].find("a") or state[0]
    states = state_tag.get_text(strip = True)

    # get the different data for years
    year2023_tag = cells[0].find("td") or cells[0]
    year2023 = year2023_tag.get_text(strip = True)

    year2024_tag = cells[2].find("td") or cells[2]
    year2024 = year2024_tag.get_text(strip = True)

    year2021_tag = cells[1].find("td") or cells[1]
    year2021 = year2021_tag.get_text(strip = True)

    # Append this data.
    rows.append({
        "States": states, 
        "Starbucks 2021": year2021,
        "Starbucks 2023": year2023,
        "Starbucks 2024": year2024
       
    })

In [30]:
starbucks = pd.DataFrame(rows)
starbucks

                  States Starbucks 2021 Starbucks 2023 Starbucks 2024
0             California          2,959          3,080          3,117
1                  Texas          1,215          1,346          1,409
2                Florida            786            844            892
3             Washington            739            741            736
4               New York            643            692            715
5               Illinois            621            677            685
6                Arizona            535            548            579
7               Colorado            497            495            506
8                   Ohio            446            491            499
9               Virginia            456            489            510
10                Oregon            345            359
11          Pennsylvania            406            357
12        North Carolina            422            338
13               Georgia            379            326
14              Michigan            310            283
15         Massachusetts            279            273
16            New Jersey            293            261
17              Maryland            274            257
18                Nevada            269            253
19               Indiana            265            221
20              Missouri            208            188
21             Minnesota            212            184
22             Tennessee            237            180
23              Kentucky            131            166
24             Wisconsin            176            145
25        South Carolina            207            131
26           Connecticut            125            123
27                  Utah            126            101
28                Hawaii            105             99
29                Kansas            120             94
30  District of Columbia                            91
31                  Iowa            142             89
32               Alabama             99             85
33             Louisiana             10             84
34              Oklahoma             94             79
35            New Mexico             92             76
36                 Idaho             78             67
37              Nebraska             87             58
38              Arkansas             66             55
39                Alaska             49             49
40           Mississippi             36             32
41               Montana             45             32
42                 Maine             31             30
43         New Hampshire             35             29
44          Rhode Island             26             27
45              Delaware             39             25
46          South Dakota             52             25
47         West Virginia             64             25
48               Wyoming             26             23
49          North Dakota             20             13
50               Vermont             35              8

In [31]:
response = requests.get("https://worldpopulationreview.com/state-rankings/dunkin-donuts-by-state")
soup = BeautifulSoup(response.content, "html.parser")
table1 = soup.find("table", class_="wpr-table")

In [32]:
#1
# initialize an empty list
rows1 = []

# iterate over all rows in the faculty table
for coffee in table1.find_all("tr")[1:]:
    state = coffee.find_all("th")
    cells = coffee.find_all("td")

    # get the state names
    state_tag = state[0].find("a") or state[0]
    states = state_tag.get_text(strip = True)

    # get the different data for years
    year2024_tag = cells[0].find("td") or cells[0]
    year2024 = year2024_tag.get_text(strip = True)

    year2023_tag = cells[1].find("td") or cells[1]
    year2023 = year2023_tag.get_text(strip = True)

    # Append this data.
    rows1.append({
        "States": states, 
        "Dunkin-Donuts 2023": year2023,
        "Dunkin-Donuts 2024": year2024,
       
    })

In [33]:
dunkin = pd.DataFrame(rows1)
dunkin

                  States Dunkin-Donuts 2023 Dunkin-Donuts 2024
0               New York              1,414              1,431
1          Massachusetts              1,068              1,042
2                Florida                883                909
3             New Jersey                866                872
4               Illinois                692                711
5           Pennsylvania                629                650
6            Connecticut                480                476
7               Maryland                303                311
8                Georgia                265                287
9                   Ohio                245                261
10              Virginia                230                244
11                 Texas                196                226
12        North Carolina                206                224
13         New Hampshire                218                216
14                 Maine                159                164
15          Rhode Island                160                159
16            California                134                143
17             Tennessee                123                137
18               Indiana                104                117
19        South Carolina                103                116
20              Michigan                105                112
21               Arizona                102                110
22             Wisconsin                 83                100
23               Alabama                 59                 69
24              Delaware                 66                 67
25              Missouri                 50                 54
26              Kentucky                 41                 50
27               Vermont                 49                 50
28              Colorado                 43                 48
29                Nevada                 38                 42
30             Minnesota                 34                 38
31                  Iowa                 34                 36
32         West Virginia                 27                 31
33                Kansas                 28                 26
34              Nebraska                 23                 24
35              Oklahoma                 18                 23
36  District of Columbia                                    19
37            New Mexico                 19                 19
38             Louisiana                 16                 15
39              Arkansas                  9                 14
40           Mississippi                 12                 14
41                Hawaii                  6                  6
42                  Utah                  1                  2
43               Wyoming                  1                  1
44                Alaska                  0                  0
45                 Idaho                  0                  0
46               Montana                  0                  0
47          North Dakota                  0                  0
48                Oregon                  0                  0
49          South Dakota                  0                  0
50            Washington                 19                  0

In [37]:
merged = starbucks.merge(dunkin, on = ["States"], 
how = "outer")
merged.head()
long = merged.melt(id_vars=["States"], value_vars=["Starbucks 2021", "Starbucks 2023", "Starbucks 2024", "Dunkin-Donuts 2023", "Dunkin-Donuts 2024"], var_name="Year_Brand", value_name="stores")
# Split the 'Year_Brand' column into 'Year' and 'Brand'
long[['Brand', 'Year']] = long['Year_Brand'].str.split(' ', expand=True)
# Drop the 'Year_Brand' column if no longer needed
long = long.drop(columns=['Year_Brand'])

            States stores          Brand  Year
0          Alabama     99      Starbucks  2021
1           Alaska     49      Starbucks  2021
2          Arizona    535      Starbucks  2021
3         Arkansas     66      Starbucks  2021
4       California  2,959      Starbucks  2021
..             ...    ...            ...   ...
250       Virginia    244  Dunkin-Donuts  2024
251     Washington      0  Dunkin-Donuts  2024
252  West Virginia     31  Dunkin-Donuts  2024
253      Wisconsin    100  Dunkin-Donuts  2024
254        Wyoming      1  Dunkin-Donuts  2024

[255 rows x 4 columns]
            States stores          Brand  Year
0          Alabama     99      Starbucks  2021
1           Alaska     49      Starbucks  2021
2          Arizona    535      Starbucks  2021
3         Arkansas     66      Starbucks  2021
4       California  2,959      Starbucks  2021
..             ...    ...            ...   ...
250       Virginia    244  Dunkin-Donuts  2024
251     Washington      0  Dunkin-Donuts  2024
252  West Virginia     31  Dunkin-Donuts  2024
253      Wisconsin    100  Dunkin-Donuts  2024
254        Wyoming      1  Dunkin-Donuts  2024

[255 rows x 4 columns]

In [39]:
response = requests.get("https://simple.wikipedia.org/wiki/List_of_U.S._states_by_population")
soup = BeautifulSoup(response.content, "html.parser")

tables = soup.find_all("table", class_ = "wikitable")

#get first table that we want
table = tables[0]

rows = []

for tr in table.find_all("tr")[1:]:
    cells = tr.find_all("td")

    # get states
    state_tag = cells[2].find("a") or cells[2]
    state = state_tag.get_text(strip = True)

    # get population
    pop_tag = cells[3].find("a") or cells[3]
    population = pop_tag.get_text(strip = True)

    # append data
    rows.append({
        "States" : state,
        "population" : population
    })

# convert to a df
population = pd.DataFrame(rows)
population.head()

withpop = long.merge(population, on = "States", how = "left")
withpop

            States stores          Brand  Year  population
0          Alabama     99      Starbucks  2021   5,024,279
1           Alaska     49      Starbucks  2021     733,391
2          Arizona    535      Starbucks  2021   7,151,502
3         Arkansas     66      Starbucks  2021   3,011,524
4       California  2,959      Starbucks  2021  39,538,223
..             ...    ...            ...   ...         ...
250       Virginia    244  Dunkin-Donuts  2024   8,631,393
251     Washington      0  Dunkin-Donuts  2024   7,705,281
252  West Virginia     31  Dunkin-Donuts  2024   1,793,716
253      Wisconsin    100  Dunkin-Donuts  2024   5,893,718
254        Wyoming      1  Dunkin-Donuts  2024     576,851

[255 rows x 5 columns]

In [40]:
withpop["Starbucks Stock Price"] = 97.21
withpop["Dunkin Stock Price"] = 106.48

In [41]:
withpop.head()

       States stores  ... Starbucks Stock Price Dunkin Stock Price
0     Alabama     99  ...                 97.21             106.48
1      Alaska     49  ...                 97.21             106.48
2     Arizona    535  ...                 97.21             106.48
3    Arkansas     66  ...                 97.21             106.48
4  California  2,959  ...                 97.21             106.48

[5 rows x 7 columns]

In [43]:
#6
state_to_region = {
    "Connecticut": "Northeast", "Maine": "Northeast", "Massachusetts": "Northeast", "New Hampshire": "Northeast",
    "New Jersey": "Northeast", "New York": "Northeast", "Pennsylvania": "Northeast", "Rhode Island": "Northeast",
    "Vermont": "Northeast",
    "Illinois": "Midwest", "Indiana": "Midwest", "Iowa": "Midwest", "Kansas": "Midwest", "Michigan": "Midwest",
    "Minnesota": "Midwest", "Missouri": "Midwest", "Nebraska": "Midwest", "North Dakota": "Midwest", 
    "Ohio": "Midwest", "South Dakota": "Midwest", "Wisconsin": "Midwest",
    "Alabama": "South", "Arkansas": "South", "Delaware": "South", "Florida": "South", "Georgia": "South",
    "Kentucky": "South", "Louisiana": "South", "Maryland": "South", "Mississippi": "South", 
    "North Carolina": "South", "Oklahoma": "South", "South Carolina": "South", "Tennessee": "South", 
    "Texas": "South", "Virginia": "South", "West Virginia": "South",
    "Alaska": "West", "Arizona": "West", "California": "West", "Colorado": "West", "Hawaii": "West",
    "Idaho": "West", "Montana": "West", "Nevada": "West", "New Mexico": "West", "Oregon": "West",
    "Utah": "West", "Washington": "West", "Wyoming": "West"
}
withpop['Region'] = withpop['States'].map(state_to_region)
withpop.head()

       States stores  ... Dunkin Stock Price Region
0     Alabama     99  ...             106.48  South
1      Alaska     49  ...             106.48   West
2     Arizona    535  ...             106.48   West
3    Arkansas     66  ...             106.48  South
4  California  2,959  ...             106.48   West

[5 rows x 8 columns]

In [46]:
# Automate
import re
def scrape_store_data(url):
    response = requests.get(url)
    soup = BeautifulSoup(response.content, "html.parser")
    
    table = soup.find("table")
    
    company_name = re.search(r'state-rankings/(.+?)-stores', url)
    company_name = company_name.group(1).replace("-", " ").title() if company_name else "Unknown"
    
    rows = []

    for coffee in table.find_all("tr")[1:]:
        state = coffee.find_all("th")
        cells = coffee.find_all("td")

        state_tag = state[0].find("a") or state[0]
        states = state_tag.get_text(strip=True)

        year2023 = cells[0].get_text(strip=True)
        year2021 = cells[1].get_text(strip=True)
        year2024 = cells[2].get_text(strip=True)

        rows.append({
            "States": states,
            f"{company_name} 2021": year2021,
            f"{company_name} 2023": year2023,
            f"{company_name} 2024": year2024
        })

    # Convert to DataFrame
    df = pd.DataFrame(rows)
    
    return df

# Example usage
url = "https://worldpopulationreview.com/state-rankings/walmart-stores-by-state"
df = scrape_store_data(url)
print(df)

IndexError: list index out of range