In [7]:
import pandas as pd
import numpy as np
xmas = pd.read_csv("https://www.dropbox.com/scl/fi/qxaslqqp5p08i1650rpc4/xmas.csv?rlkey=erdxi7jbh7pqf9fh4lv4cayp5&dl=1")
xmas

    Day Day.in.Words  Gift.Item        Verb Adjective        Location
0     1        first  partridge         NaN       NaN  in a pear tree
1     2       second       dove         NaN    turtle             NaN
2     3        third        hen         NaN    french             NaN
3     4       fourth       bird         NaN   calling             NaN
4     5        fifth       ring         NaN    golden             NaN
5     6        sixth      goose    a-laying       NaN             NaN
6     7      seventh       swan  a-swimming       NaN             NaN
7     8       eighth       maid   a-milking       NaN             NaN
8     9        ninth       lady     dancing       NaN             NaN
9    10        tenth       lord   a-leaping       NaN             NaN
10   11     eleventh      piper      piping       NaN             NaN
11   12      twelfth    drummer    drumming       NaN             NaN

In [8]:
def pluralize_gift(gift):
  """
  Returns plural of a noun
  
  Parameters
  ----------
  gift: str
    A noun
    
  Return
  ------
  str
    Plural version
  """

  if "oo" in gift:
    gift = gift.replace("oo","ee")
  elif gift.endswith("y"):
    gift = gift[:-1] + "ies"
  else:
    gift = gift + "s"

  return gift

In [9]:
pluralize_gift = np.vectorize(pluralize_gift)

In [11]:
# Should work
pluralize_gift("goose")

# Will work if your function is vectorized! 
pluralize_gift(xmas['Gift.Item'])

array(['partridges', 'doves', 'hens', 'birds', 'rings', 'geese', 'swans',
       'maids', 'ladies', 'lords', 'pipers', 'drummers'], dtype='<U10')

In [ ]:
def make_phrase(num, num_word, item, verb, adjective, location):
  """
  <documentation here>
  """
  
  ## Step 1: Replace NAs with blank strings
  verb = verb.fillna("")
  adjective = adjective.fillna("")
  location = location.fillna("")
  
  ## Step 2: If the day number is larger than 1, the gift items need pluralized!
  ### Hint: call the function you created above!
  if day > 1:
    item = pluralize_gift(item).item()
  
  ## Step 3: Figure out if a gift item starts with a vowel
  vowels = 'aeiou'
  vowel = item[0] in vowel

  ## Step 4: For the first day, if the gift item starts with a vowel, replace the day with "an" and if the gift item does not start with a vowel, replace the day with "a" (e.g. a partridge in a pear tree). If it is not the first day, use just the number word (e.g. ten lords a leap)
  if Day == 1:
    replace = "an" if vowel = True else "a"
  else:
    replace = Day.in.words

  ## Step 5: Put all of the pieces together into one string and return!

In [15]:
def make_phrase(day, num_word, item, verb, adjective, location):
    """
    <documentation here>
    """
    
    ## Step 1: Replace NAs with blank strings
    verb = verb if verb is not None else ""
    adjective = adjective if adjective is not None else ""
    location = location if location is not None else ""
    
    ## Step 2: If the day number is larger than 1, the gift items need pluralized!
    ### Hint: call the function you created above!
    if day > 1:
        item = pluralize_gift(item)  # Assuming pluralize_gift returns the pluralized form
  
    ## Step 3: Figure out if a gift item starts with a vowel
    vowels = 'aeiou'
    vowel = item[0].lower() in vowels if item else False  # Check for empty item

    ## Step 4: For the first day, determine the article ("a" or "an")
    if day == 1:
        replace = "an" if vowel else "a"
    else:
        replace = num_word  # Use the number word for days greater than 1

    ## Step 5: Put all of the pieces together into one string and return!
    phrase = f"{replace} {item} {verb} {adjective} {location}".strip()
    return phrase